//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Front page</summary>
	[PublishedContentModel("frontPage2")]
	public partial class FrontPage2 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "frontPage2";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FrontPage2(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FrontPage2, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Extra
		///</summary>
		[ImplementPropertyType("extrafrontpage")]
		public IEnumerable<IPublishedContent> Extrafrontpage
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("extrafrontpage"); }
		}

		///<summary>
		/// Footer text
		///</summary>
		[ImplementPropertyType("footerText")]
		public IHtmlString FooterText
		{
			get { return this.GetPropertyValue<IHtmlString>("footerText"); }
		}

		///<summary>
		/// Nested content
		///</summary>
		[ImplementPropertyType("nestedThemesContent")]
		public IEnumerable<IPublishedContent> NestedThemesContent
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("nestedThemesContent"); }
		}

		///<summary>
		/// References
		///</summary>
		[ImplementPropertyType("referencesPost")]
		public IHtmlString ReferencesPost
		{
			get { return this.GetPropertyValue<IHtmlString>("referencesPost"); }
		}

		///<summary>
		/// Summary
		///</summary>
		[ImplementPropertyType("summaryPost")]
		public IHtmlString SummaryPost
		{
			get { return this.GetPropertyValue<IHtmlString>("summaryPost"); }
		}

		///<summary>
		/// Main Description
		///</summary>
		[ImplementPropertyType("themesFrontPageDescription")]
		public IHtmlString ThemesFrontPageDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("themesFrontPageDescription"); }
		}
	}
}
