//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>NewSpeaker</summary>
	[PublishedContentModel("newSpeakerPost")]
	public partial class NewSpeakerPost : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "newSpeakerPost";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NewSpeakerPost(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NewSpeakerPost, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("SpeakerDescriptionPost")]
		public IHtmlString SpeakerDescriptionPost
		{
			get { return this.GetPropertyValue<IHtmlString>("SpeakerDescriptionPost"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("SpeakernamePost")]
		public string SpeakernamePost
		{
			get { return this.GetPropertyValue<string>("SpeakernamePost"); }
		}

		///<summary>
		/// Speaker Picture
		///</summary>
		[ImplementPropertyType("speakerPicturePost")]
		public IPublishedContent SpeakerPicturePost
		{
			get { return this.GetPropertyValue<IPublishedContent>("speakerPicturePost"); }
		}

		///<summary>
		/// voting number
		///</summary>
		[ImplementPropertyType("votingNumber")]
		public int VotingNumber
		{
			get { return this.GetPropertyValue<int>("votingNumber"); }
		}

		///<summary>
		/// voting score
		///</summary>
		[ImplementPropertyType("votingScore")]
		public int VotingScore
		{
			get { return this.GetPropertyValue<int>("votingScore"); }
		}
	}
}
