//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1081 with alias "newSpeakerPost"
	/// <summary>NewSpeaker</summary>
	public partial interface INewSpeakerPost : IPublishedContent
	{
		/// <summary>Description</summary>
		IHtmlString SpeakerDescriptionPost { get; }

		/// <summary>Name</summary>
		string SpeakernamePost { get; }

		/// <summary>Speaker Picture</summary>
		IPublishedContent SpeakerPicturePost { get; }
	}

	/// <summary>NewSpeaker</summary>
	[PublishedContentModel("newSpeakerPost")]
	public partial class NewSpeakerPost : PublishedContentModel, INewSpeakerPost
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "newSpeakerPost";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NewSpeakerPost(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NewSpeakerPost, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("SpeakerDescriptionPost")]
		public IHtmlString SpeakerDescriptionPost
		{
			get { return GetSpeakerDescriptionPost(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static IHtmlString GetSpeakerDescriptionPost(INewSpeakerPost that) { return that.GetPropertyValue<IHtmlString>("SpeakerDescriptionPost"); }

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("SpeakernamePost")]
		public string SpeakernamePost
		{
			get { return GetSpeakernamePost(this); }
		}

		/// <summary>Static getter for Name</summary>
		public static string GetSpeakernamePost(INewSpeakerPost that) { return that.GetPropertyValue<string>("SpeakernamePost"); }

		///<summary>
		/// Speaker Picture
		///</summary>
		[ImplementPropertyType("speakerPicturePost")]
		public IPublishedContent SpeakerPicturePost
		{
			get { return GetSpeakerPicturePost(this); }
		}

		/// <summary>Static getter for Speaker Picture</summary>
		public static IPublishedContent GetSpeakerPicturePost(INewSpeakerPost that) { return that.GetPropertyValue<IPublishedContent>("speakerPicturePost"); }
	}
}
